import Link from "next/link";
import { useEffect, useId, useRef, useState, type KeyboardEvent } from "react";

import type { CoachSummaryResponse, DailyPlanResponse, ExamCode, PerformanceTrendsResponse, ProgressHistoryResponse, ProgressSummaryResponse, RevisionDueResponse, RevisionRecommendationItem, SubjectCode } from "../lib/api";
import TodayPlan from "./planning/TodayPlan";
import { Badge, Button, Card, EmptyState, ErrorState, Skeleton, StatusPanel } from "./ui";
import styles from "./progress/ProgressDashboard.module.css";

type ProgressDashboardProps={exam:ExamCode;subject:SubjectCode;summary:ProgressSummaryResponse|null;history:ProgressHistoryResponse|null;dailyPlan:DailyPlanResponse|null;revisionDue:RevisionDueResponse|null;coachSummary:CoachSummaryResponse|null;trends:PerformanceTrendsResponse|null;loading:boolean;refreshing:boolean;error:string|null;onRefresh:()=>void};
type TabId="trends"|"revision"|"coach"|"history";
const tabs:[TabId,string][]=[["trends","Trends"],["revision","Revision"],["coach","Coach"],["history","History"]];

function safePercent(value:number){return Math.round(Math.max(0,Math.min(100,Number.isFinite(value)?value:0)))}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.valueOf())?"Date unavailable":new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(date)}
function toneForTrend(value:string):"primary"|"accent"|"neutral"{return value==="improving"?"primary":value==="declining"?"accent":"neutral"}

function ProgressBar({label,value}:{label:string;value:number}){const normalized=safePercent(value);return <div className={styles.progressMeasure}><div><span>{label}</span><strong>{normalized}%</strong></div><div className={styles.progressTrack} role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={normalized}><span style={{width:`${normalized}%`}}/></div></div>}

function RevisionQueue({items,exam,subject}:{items:RevisionRecommendationItem[];exam:ExamCode;subject:SubjectCode}){if(!items.length)return <EmptyState title="Revision is clear" message="Nothing is due right now. Keep the next study loop focused and the queue will update from real performance evidence." action={<Link href={{pathname:"/tutor",query:{exam,subject}}}><Button>Continue studying</Button></Link>}/>;return <div className={styles.queue}>{items.map((item,index)=><article className={styles.queueItem} key={`${item.topic}-${item.due_at}-${index}`}><div className={styles.queueTop}><div><span className={styles.kicker}>{item.chapter}</span><h3>{item.topic}</h3></div><Badge tone={item.status==="overdue"?"accent":"neutral"}>{item.status.replace(/_/g," ")}</Badge></div><p>{item.reason}</p><dl className={styles.inlineFacts}><div><dt>Signal</dt><dd>{item.revision_signal.replace(/_/g," ")}</dd></div>{item.mastery_score!=null?<div><dt>Mastery</dt><dd>{safePercent(item.mastery_score)}%</dd></div>:null}<div><dt>Session</dt><dd>{item.recommended_session_mode.replace(/_/g," ")}</dd></div></dl><Link href={{pathname:"/tutor",query:{exam,subject,topic:item.topic,mode:"revision"}}}>Start revision</Link></article>)}</div>}

function TrendsPanel({trends,summary}:{trends:PerformanceTrendsResponse|null;summary:ProgressSummaryResponse|null}){if(!trends&&!summary)return <EmptyState title="No trend yet" message="Two or more quiz-backed study signals will make this view useful."/>;const items=trends?.topics??[];return <section aria-labelledby="trends-panel-title"><div className={styles.panelHeading}><div><span className={styles.kicker}>Performance movement</span><h2 id="trends-panel-title">Trends</h2></div><Badge tone={toneForTrend(trends?.overall_trend||summary?.progress_insights.momentum_status||"stable")}>{(trends?.overall_trend||summary?.progress_insights.momentum_status||"building").replace(/_/g," ")}</Badge></div><p className={styles.lead}>{trends?.overall_reason||summary?.progress_insights.momentum_summary}</p>{trends?<div className={styles.compare}><ProgressBar label="Recent average" value={trends.recent_average}/><ProgressBar label="Previous average" value={trends.previous_average}/></div>:null}{items.length?<div className={styles.trendList}>{items.slice(0,8).map(item=><article key={`${item.chapter}-${item.topic}`}><div><strong>{item.topic}</strong><span>{item.chapter}</span></div><Badge tone={toneForTrend(item.trend)}>{item.trend}</Badge><p>{item.insight}</p><span className={styles.delta}>{item.accuracy_delta>0?"+":""}{Math.round(item.accuracy_delta)} percentage points</span></article>)}</div>:<p className={styles.muted}>Topic-level movement will appear after more quiz history.</p>}</section>}

function CoachPanel({coach,plan,exam,subject}:{coach:CoachSummaryResponse|null;plan:DailyPlanResponse|null;exam:ExamCode;subject:SubjectCode}){if(!coach&&!plan)return <EmptyState title="Coach needs more evidence" message="Complete a lesson or quiz to create a useful recommendation."/>;const title=coach?.study_today||plan?.focus_topic||"Take one focused step";const reason=coach?.study_reason||plan?.focus_reason||"Build one useful signal before widening the plan.";const action=coach?.next_action||plan?.next_action||"Open Tutor and complete one study loop.";const mode=coach?.recommended_mode||plan?.recommended_mode||"study";return <section aria-labelledby="coach-panel-title"><div className={styles.panelHeading}><div><span className={styles.kicker}>Evidence-led guidance</span><h2 id="coach-panel-title">Coach</h2></div><Badge>{mode}</Badge></div><Card className={styles.coachFocus}><h3>{title}</h3><p>{reason}</p><strong>{action}</strong><Link href={{pathname:mode==="quiz"?"/test":"/tutor",query:{exam,subject,topic:title}}}><Button>Take the next step</Button></Link></Card><details className={styles.disclosure}><summary>Why this recommendation?</summary><p>{coach?.recommended_reason||coach?.trend_reason||plan?.recommended_difficulty_reason||"The recommendation uses the study and quiz evidence currently available."}</p>{coach?.warnings.length?<ul>{coach.warnings.map(item=><li key={item.title}><strong>{item.title}:</strong> {item.message}</li>)}</ul>:null}</details></section>}

function HistoryPanel({history}:{history:ProgressHistoryResponse|null}){const rows=history?.history??[];if(!rows.length)return <EmptyState title="No quiz history yet" message="Your submitted quizzes will appear here with topic, difficulty, date, and accuracy."/>;return <section aria-labelledby="history-panel-title"><div className={styles.panelHeading}><div><span className={styles.kicker}>Recent evidence</span><h2 id="history-panel-title">Study history</h2></div><Badge tone="neutral">{rows.length} attempts</Badge></div><div className={styles.tableWrap}><table><caption className="visually-hidden">Recent quiz attempts</caption><thead><tr><th scope="col">Topic</th><th scope="col">Date</th><th scope="col">Difficulty</th><th scope="col">Score</th><th scope="col">Accuracy</th></tr></thead><tbody>{rows.slice(0,20).map(item=><tr key={item.id}><th scope="row"><strong>{item.topic}</strong><span>{item.chapter}</span></th><td>{formatDate(item.created_at)}</td><td>{item.difficulty}</td><td>{item.score}/{item.total_questions}</td><td>{safePercent(item.accuracy)}%</td></tr>)}</tbody></table></div>{rows.length>20?<p className={styles.muted}>Showing the 20 most recent attempts.</p>:null}</section>}

export default function ProgressDashboard({exam,subject,summary,history,dailyPlan,revisionDue,coachSummary,trends,loading,refreshing,error,onRefresh}:ProgressDashboardProps){const [active,setActive]=useState<TabId>("trends");const id=useId();const refs=useRef<Record<TabId,HTMLButtonElement|null>>({trends:null,revision:null,coach:null,history:null});const tutorHref=`/tutor?exam=${encodeURIComponent(exam)}&subject=${encodeURIComponent(subject)}`;const testHref=`/test?exam=${encodeURIComponent(exam)}&subject=${encodeURIComponent(subject)}`;const attempts=summary?.recent_quizzes.length??history?.history.length??0;const average=summary?.recent_quizzes.length?summary.recent_quizzes.reduce((sum,item)=>sum+item.accuracy,0)/summary.recent_quizzes.length:history?.history.length?history.history.reduce((sum,item)=>sum+item.accuracy,0)/history.history.length:0;const revisionItems=revisionDue?[...revisionDue.overdue,...revisionDue.due_now,...revisionDue.due_soon]:summary?.revision_recommendations??[];
 useEffect(()=>{const requested=window.location.hash.slice(1) as TabId;if(tabs.some(([tab])=>tab===requested))setActive(requested)},[]);
 const onKeys=(event:KeyboardEvent<HTMLButtonElement>,current:TabId)=>{const index=tabs.findIndex(([key])=>key===current);let next=index;if(event.key==="ArrowRight")next=(index+1)%tabs.length;else if(event.key==="ArrowLeft")next=(index-1+tabs.length)%tabs.length;else if(event.key==="Home")next=0;else if(event.key==="End")next=tabs.length-1;else return;event.preventDefault();const nextId=tabs[next][0];setActive(nextId);refs.current[nextId]?.focus()};
 if(loading)return <section className={styles.loading} aria-label="Loading progress"><Skeleton height={140}/><div className={styles.metricGrid}>{[1,2,3,4].map(item=><Skeleton key={item} height={110}/>)}</div><Skeleton height={300}/></section>;
 if(error&&!summary&&!history)return <ErrorState title="Progress is unavailable" message={error} action={<Button onClick={onRefresh}>Try again</Button>}/>;
 return <div className={styles.dashboard}>{error?<StatusPanel tone="warning" title="Some insights are unavailable" message={error} actions={<Button variant="secondary" loading={refreshing} onClick={onRefresh}>Retry missing insights</Button>}/>:null}<section className={styles.overview} aria-labelledby="progress-overview-title"><div className={styles.overviewHeading}><div><span className={styles.kicker}>At a glance</span><h2 id="progress-overview-title">Progress overview</h2></div><Button variant="ghost" loading={refreshing} onClick={onRefresh}>Refresh</Button></div><div className={styles.metricGrid}><Card><strong>{attempts}</strong><span>Quiz attempts</span></Card><Card><strong>{attempts?`${safePercent(average)}%`:"—"}</strong><span>Recent accuracy</span></Card><Card><strong>{summary?.mastery_overview.ready_count??0}</strong><span>Topics ready</span></Card><Card><strong>{revisionDue?.total_due_count??revisionItems.length}</strong><span>Revision due</span></Card></div><p className={styles.interpretation}>{summary?.study_profile.profile_summary||trends?.overall_reason||"Complete a quiz to turn activity into a meaningful progress signal."}</p></section><TodayPlan variant="expanded" plan={dailyPlan} tutorHref={tutorHref} testHref={testHref}/><section className={styles.sections} aria-label="Detailed progress"><div className={styles.tabList} role="tablist" aria-label="Progress sections">{tabs.map(([tab,label])=><button key={tab} ref={node=>{refs.current[tab]=node}} id={`${id}-${tab}-tab`} type="button" role="tab" aria-selected={active===tab} aria-controls={`${id}-${tab}-panel`} tabIndex={active===tab?0:-1} onClick={()=>setActive(tab)} onKeyDown={event=>onKeys(event,tab)}>{label}{tab==="revision"&&revisionItems.length?<span>{revisionItems.length}</span>:null}</button>)}</div><div className={styles.panel} id={`${id}-${active}-panel`} role="tabpanel" tabIndex={0} aria-labelledby={`${id}-${active}-tab`}>{active==="trends"?<TrendsPanel trends={trends} summary={summary}/>:active==="revision"?<RevisionQueue items={revisionItems} exam={exam} subject={subject}/>:active==="coach"?<CoachPanel coach={coachSummary} plan={dailyPlan} exam={exam} subject={subject}/>:<HistoryPanel history={history}/>}</div></section></div>}
