import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useMemo, useRef, useState } from "react";

import { AuthFeatureGrid } from "../components/auth/AuthFeatureGrid";
import { AuthHero } from "../components/auth/AuthHero";
import { AuthProof } from "../components/auth/AuthProof";
import { ExamDestinationCards } from "../components/auth/ExamDestinationCards";
import { OtpSignInCard } from "../components/auth/OtpSignInCard";
import { ProductPreview } from "../components/auth/ProductPreview";
import type { AuthStepState } from "../components/auth/AuthStepIndicator";
import styles from "../components/auth/AuthExperience.module.css";
import PublicShell from "../components/PublicShell";
import { DEFAULT_EXAM, DEFAULT_SUBJECT, requestOtp, updateUserProfile, type AuthSessionResponse } from "../lib/api";
import { deriveOnboardingFlowState, useAuth } from "../lib/auth";
import { buildPublicExamAuthHref, getPublicExamLandings, type PublicExamLandingSlug } from "../lib/public-exams";
import { buildOrganizationStructuredData, buildPublicPageMetadata, buildSoftwareApplicationStructuredData, serializeStructuredData } from "../lib/seo";

type OtpRequestState = { maskedEmail:string; challengeExpiresAt:string; resendAvailableAt:string; deliveryMode:"console"|"email"; devOtpCode:string|null; isNewUser:boolean };
const EXAM_CARD_ORDER:PublicExamLandingSlug[]=["upsc","ssc","banking"];
const EXAM_CARD_COPY:Record<PublicExamLandingSlug,{title:string;description:string}>={
  upsc:{title:"UPSC CSE",description:"The deepest native corpus, with concept-first General Studies support."},
  ssc:{title:"SSC",description:"Concise general awareness with shared-corpus support where marked."},
  banking:{title:"Banking",description:"Financial awareness and regulation basics with shared support."},
};

function formatCountdown(targetIso:string,now:number){const target=Date.parse(targetIso);if(Number.isNaN(target))return null;const left=Math.max(Math.ceil((target-now)/1000),0);if(!left)return null;const minutes=Math.floor(left/60),seconds=left%60;return minutes?`${minutes}m ${seconds.toString().padStart(2,"0")}s`:`${seconds}s`}
function isExpired(targetIso:string,now:number){const target=Date.parse(targetIso);return !Number.isNaN(target)&&target<=now}
function normalizeOtpCode(value:string){return value.replace(/\D/g,"").slice(0,6)}
function safeNextPath(value:unknown){if(typeof value!=="string")return "/";const path=value.trim();return path.startsWith("/")&&!path.startsWith("//")&&!path.includes("\\")&&!/[\u0000-\u001f]/.test(path)?path:"/"}
function friendlyError(error:unknown,fallback:string){const message=(error instanceof Error?error.message:fallback).trim(),lower=message.toLowerCase();if(lower.includes("too many")||lower.includes("rate")||lower.includes("wait")||lower.includes("cooldown"))return "Too many sign-in attempts were made too quickly. Wait for the cooldown, then request a fresh code.";if(lower.includes("valid email")||lower.includes("invalid email"))return "Enter a valid email address so Adhyantra can send the sign-in code.";if(lower.includes("expired"))return "That sign-in code has expired. Request a fresh code and use the newest one.";if(lower.includes("invalid")||lower.includes("incorrect")||lower.includes("attempt"))return "That code did not match. Check the latest code and try again before it expires.";if(lower.includes("email")||lower.includes("deliver")||lower.includes("smtp"))return "Adhyantra could not deliver the sign-in email right now. Please try again in a moment.";if(lower.includes("backend")||lower.includes("network")||lower.includes("fetch"))return "Adhyantra is having trouble connecting right now. Please try again in a moment.";return message||fallback}
function errorTitle(message:string){const lower=message.toLowerCase();if(lower.includes("email address")||lower.includes("valid email"))return "Check your email address";if(lower.includes("expired"))return "Code expired";if(lower.includes("too many")||lower.includes("cooldown")||lower.includes("wait"))return "Please wait";if(lower.includes("deliver"))return "Email delivery issue";return "Sign-in needs attention"}
function destinationLabel(path:string){if(path.startsWith("/progress"))return "Progress";if(path.startsWith("/test"))return "Test";if(path.startsWith("/tutor"))return "Tutor";if(path.startsWith("/settings"))return "Settings";return "Home"}
function onboardingPath(nextPath:string){const params=new URLSearchParams({onboarding:"welcome"});if(nextPath!=="/"&&!nextPath.startsWith("/settings"))params.set("next",nextPath);return `/settings?${params.toString()}`}
function mentorMode(value:string|null|undefined){return value==="strict"?"strict":"normal"}
function firstSessionPath(exam:string|null|undefined,subject:string|null|undefined,mode:string|null|undefined){const params=new URLSearchParams({exam:exam||DEFAULT_EXAM,subject:subject||DEFAULT_SUBJECT,mentor_mode:mentorMode(mode),welcome:"first-session"});return `/?${params.toString()}`}
function firstSessionPathFromSession(session:AuthSessionResponse){return firstSessionPath(session.settings.current_exam||session.settings.preferred_exam,session.settings.current_subject||session.settings.preferred_subject,session.settings.mentor_mode)}
function examFromNext(path:string):PublicExamLandingSlug|null{const query=path.indexOf("?");if(query<0)return null;const exam=new URLSearchParams(path.slice(query+1)).get("exam");return exam==="upsc"||exam==="ssc"||exam==="banking"?exam:null}

export default function AuthPage(){
  const router=useRouter();const {completeOtpSignIn}=useAuth();
  const [email,setEmail]=useState("");const [displayName,setDisplayName]=useState("");const [otpCode,setOtpCode]=useState("");const [requestState,setRequestState]=useState<OtpRequestState|null>(null);const [selectedExam,setSelectedExam]=useState<PublicExamLandingSlug>("upsc");const [submittingEmail,setSubmittingEmail]=useState(false);const [submittingCode,setSubmittingCode]=useState(false);const [feedback,setFeedback]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [complete,setComplete]=useState(false);const [clock,setClock]=useState(()=>Date.now());const [announcement,setAnnouncement]=useState("");
  const emailRef=useRef<HTMLInputElement>(null),otpRef=useRef<HTMLInputElement>(null),resendWasReady=useRef(false);
  const nextPath=useMemo(()=>safeNextPath(router.query.next),[router.query.next]);const nextLabel=useMemo(()=>destinationLabel(nextPath),[nextPath]);
  const examLinks=useMemo(()=>getPublicExamLandings().map((landing)=>({slug:landing.slug,label:EXAM_CARD_COPY[landing.slug].title,href:buildPublicExamAuthHref(landing.slug),summary:EXAM_CARD_COPY[landing.slug].description})).sort((a,b)=>EXAM_CARD_ORDER.indexOf(a.slug)-EXAM_CARD_ORDER.indexOf(b.slug)),[]);
  const metadata=useMemo(()=>buildPublicPageMetadata({title:"Focused exam preparation with a clear next step",description:"AI-guided explanations, quizzes, revision planning and progress tracking for UPSC, SSC and Banking learners.",canonicalPath:"/auth"}),[]);
  const structured=useMemo(()=>[buildOrganizationStructuredData(),buildSoftwareApplicationStructuredData({title:metadata.title,description:metadata.description,canonicalUrl:metadata.canonicalUrl})],[metadata]);

  useEffect(()=>{if(!requestState)return;const timer=window.setInterval(()=>setClock(Date.now()),1000);return()=>window.clearInterval(timer)},[requestState]);
  useEffect(()=>{const selected=examFromNext(nextPath);if(selected)setSelectedExam(selected)},[nextPath]);
  useEffect(()=>{if(requestState)window.requestAnimationFrame(()=>otpRef.current?.focus())},[requestState]);
  const resendCountdown=requestState?formatCountdown(requestState.resendAvailableAt,clock):null;const challengeCountdown=requestState?formatCountdown(requestState.challengeExpiresAt,clock):null;const challengeExpired=requestState?isExpired(requestState.challengeExpiresAt,clock):false;
  useEffect(()=>{const ready=Boolean(requestState&&!resendCountdown);if(ready&&!resendWasReady.current){setAnnouncement("You can now request a new sign-in code.")}resendWasReady.current=ready},[requestState,resendCountdown]);
  const steps:{step:string;label:string;state:AuthStepState}[]=[{step:"1",label:"Email",state:requestState?"complete":"active"},{step:"2",label:"Verify",state:complete?"complete":requestState?"active":"pending"},{step:"3",label:"Enter",state:complete?"active":"pending"}];

  async function handleRequest(){const target=email.trim().toLowerCase();if(!target){setError("Enter your email address to get a sign-in code.");emailRef.current?.focus();return}setSubmittingEmail(true);setError(null);setFeedback(null);setComplete(false);try{const response=await requestOtp(target);setEmail(response.email||target);setRequestState({maskedEmail:response.masked_email,challengeExpiresAt:response.challenge_expires_at,resendAvailableAt:response.resend_available_at,deliveryMode:response.delivery_mode,devOtpCode:response.dev_otp_code,isNewUser:response.is_new_user});if(!response.is_new_user)setDisplayName("");setOtpCode("");setClock(Date.now());setFeedback(response.delivery_mode==="email"?`Code sent to ${response.masked_email}.`:response.dev_otp_code?`A local sign-in code is ready for ${response.masked_email}.`:`Use the latest local test code for ${response.masked_email}.`);setAnnouncement("Sign-in code requested. Enter the latest six-digit code.")}catch(reason){const message=friendlyError(reason,"Could not send the sign-in code.");setError(message);setAnnouncement(message)}finally{setSubmittingEmail(false)}}
  async function handleVerify(){if(!requestState)return;if(challengeExpired){const message="That code has expired. Request a fresh code before continuing.";setError(message);setAnnouncement(message);return}const code=normalizeOtpCode(otpCode);if(code.length!==6){const message="Enter the full 6-digit sign-in code.";setError(message);setAnnouncement(message);otpRef.current?.focus();return}setSubmittingCode(true);setError(null);setFeedback(null);try{const session=await completeOtpSignIn(email.trim().toLowerCase(),code);if(requestState.isNewUser&&displayName.trim()){try{await updateUserProfile({display_name:displayName.trim()})}catch{/* Settings collects this optional name later. */}}const onboarding=deriveOnboardingFlowState(session),setup=requestState.isNewUser||onboarding.needsSetup,first=!setup&&nextPath==="/"&&!session.user.activation?.activated;const destination=setup&&!nextPath.startsWith("/settings")?onboardingPath(nextPath):first?firstSessionPathFromSession(session):nextPath;setComplete(true);const message=setup?(nextPath.startsWith("/settings")?"Sign-in confirmed. Opening Settings.":`Sign-in confirmed. Opening Settings, then ${nextLabel}.`):first?"Sign-in confirmed. Opening Home.":`Sign-in confirmed. Opening ${nextLabel}.`;setFeedback(message);setAnnouncement(message);await router.replace(destination)}catch(reason){setOtpCode("");const message=friendlyError(reason,"Could not verify the sign-in code.");setError(message);setAnnouncement(message);window.requestAnimationFrame(()=>otpRef.current?.focus())}finally{setSubmittingCode(false)}}
  function changeEmail(){setRequestState(null);setOtpCode("");setFeedback(null);setError(null);setComplete(false);setAnnouncement("Email address can now be changed.");window.requestAnimationFrame(()=>emailRef.current?.focus())}

  return <><Head><title>{`${metadata.title} | ${metadata.siteName}`}</title><meta name="description" content={metadata.description}/>{metadata.canonicalUrl?<link rel="canonical" href={metadata.canonicalUrl}/>:null}<meta property="og:site_name" content={metadata.siteName}/><meta property="og:type" content={metadata.openGraphType}/><meta property="og:title" content={metadata.title}/><meta property="og:description" content={metadata.description}/>{metadata.canonicalUrl?<meta property="og:url" content={metadata.canonicalUrl}/>:null}<meta name="twitter:card" content={metadata.twitterCard}/><meta name="twitter:title" content={metadata.title}/><meta name="twitter:description" content={metadata.description}/>{structured.map((node,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeStructuredData(node)}}/>)}</Head><PublicShell compactFooter><main className={styles.page}><div className={styles.launchGrid}><div className={styles.launchStory}><AuthHero/><ExamDestinationCards items={examLinks} selected={selectedExam} onSelect={(item)=>{setSelectedExam(item.slug);void router.replace(item.href,undefined,{shallow:true})}}/></div><OtpSignInCard email={email} displayName={displayName} otpCode={otpCode} requestState={requestState} submittingEmail={submittingEmail} submittingCode={submittingCode} signInComplete={complete} challengeExpired={challengeExpired} challengeCountdown={challengeCountdown} resendCountdown={resendCountdown} feedback={feedback} error={error} errorTitle={errorTitle(error||"")} announcement={announcement} emailRef={emailRef} otpRef={otpRef} steps={steps} onEmailChange={setEmail} onDisplayNameChange={setDisplayName} onOtpChange={(value)=>setOtpCode(normalizeOtpCode(value))} onRequest={()=>void handleRequest()} onVerify={()=>void handleVerify()} onResend={()=>void handleRequest()} onChangeEmail={changeEmail}/><ProductPreview/></div><div className={styles.supporting}><AuthFeatureGrid/><AuthProof/></div></main></PublicShell></>;
}
