import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/router";

import StudyContextControls from "../components/dashboard/StudyContextControls";
import ProgressDashboard from "../components/ProgressDashboard";
import { PageHeader } from "../components/ui";
import { DEFAULT_EXAM, DEFAULT_SUBJECT, getCoachSummary, getPerformanceTrends, getProgressHistory, getProgressSummary, getRevisionDue, getTodayPlan, type CoachSummaryResponse, type DailyPlanResponse, type ExamCode, type MentorMode, type PerformanceTrendsResponse, type ProgressHistoryResponse, type ProgressSummaryResponse, type RevisionDueResponse, type SubjectCode } from "../lib/api";
import { useAuth } from "../lib/auth";
import { resolvePersistedExamContext, resolvePreferredSubjectForExam } from "../lib/exam-preferences";
import { persistStudySettings } from "../lib/settings-persistence";
import { useSubjects } from "../lib/useSubjects";
import styles from "../styles/ProgressPage.module.css";

function normalizeMentorMode(value:string|null|undefined):MentorMode{return value==="strict"?"strict":"normal"}
function normalizeExamCode(value:string|null|undefined):ExamCode{return (value||"").trim().toLowerCase()||DEFAULT_EXAM}

export default function ProgressPage(){
 const router=useRouter();const {session,updateSettings}=useAuth();const requestRef=useRef(0);
 const [exam,setExam]=useState<ExamCode>(DEFAULT_EXAM);const {subjects,exams,defaultExam,defaultSubject}=useSubjects(exam);const [subject,setSubject]=useState<SubjectCode>(DEFAULT_SUBJECT);const [mentorMode,setMentorMode]=useState<MentorMode>("normal");
 const [summary,setSummary]=useState<ProgressSummaryResponse|null>(null);const [history,setHistory]=useState<ProgressHistoryResponse|null>(null);const [plan,setPlan]=useState<DailyPlanResponse|null>(null);const [revision,setRevision]=useState<RevisionDueResponse|null>(null);const [coach,setCoach]=useState<CoachSummaryResponse|null>(null);const [trends,setTrends]=useState<PerformanceTrendsResponse|null>(null);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(!router.isReady)return;const querySubject=typeof router.query.subject==="string"?router.query.subject.trim():"";const queryExam=typeof router.query.exam==="string"?normalizeExamCode(router.query.exam):null;const queryMentor=typeof router.query.mentor_mode==="string"?normalizeMentorMode(router.query.mentor_mode):null;const persisted=resolvePersistedExamContext(session?.settings,{defaultExam,defaultSubject});setExam(queryExam||persisted.exam);setMentorMode(queryMentor||persisted.mentorMode);setSubject(querySubject||(queryExam?resolvePreferredSubjectForExam(exams,queryExam,persisted.subject):persisted.subject)||DEFAULT_SUBJECT)},[defaultExam,defaultSubject,exams,router.isReady,router.query.exam,router.query.mentor_mode,router.query.subject,session?.settings]);
 useEffect(()=>{const available=subjects.filter(item=>item.available);const options=available.length?available:subjects;if(!options.length||options.some(item=>item.code===subject))return;const next=defaultSubject||options[0].code;setSubject(next);persistStudySettings(updateSettings,{current_exam:exam,current_subject:next},"progress context")},[defaultSubject,exam,subject,subjects,updateSettings]);
 const load=useCallback(async(initial=false)=>{const id=++requestRef.current;initial?setLoading(true):setRefreshing(true);const results=await Promise.allSettled([getProgressSummary(subject,mentorMode,exam),getProgressHistory(subject,exam),getTodayPlan(subject,mentorMode,exam),getRevisionDue(subject,exam),getCoachSummary(subject,mentorMode,exam),getPerformanceTrends(subject,exam)]);if(id!==requestRef.current)return;const [summaryResult,historyResult,planResult,revisionResult,coachResult,trendsResult]=results;if(summaryResult.status==="fulfilled")setSummary(summaryResult.value);if(historyResult.status==="fulfilled")setHistory(historyResult.value);if(planResult.status==="fulfilled")setPlan(planResult.value);if(revisionResult.status==="fulfilled")setRevision(revisionResult.value);if(coachResult.status==="fulfilled")setCoach(coachResult.value);if(trendsResult.status==="fulfilled")setTrends(trendsResult.value);if(summaryResult.status==="rejected"&&historyResult.status==="rejected")setError("Could not load core progress or history right now.");else if(summaryResult.status==="rejected")setError("The progress summary is temporarily unavailable. Recent history remains visible.");else if(historyResult.status==="rejected")setError("Recent history is temporarily unavailable. Your progress summary remains visible.");else setError(results.slice(2).some(result=>result.status==="rejected")?"Some coaching insights are temporarily unavailable, but core progress is still shown.":null);setLoading(false);setRefreshing(false)},[exam,mentorMode,subject]);
 useEffect(()=>{setSummary(null);setHistory(null);setPlan(null);setRevision(null);setCoach(null);setTrends(null);setError(null);void load(true);return()=>{requestRef.current+=1}},[load,session?.user.id]);
 const replaceContext=(nextExam:ExamCode,nextSubject:SubjectCode,nextMentor:MentorMode)=>{if(router.isReady)void router.replace({pathname:router.pathname,query:{...router.query,exam:nextExam,subject:nextSubject,mentor_mode:nextMentor}},undefined,{shallow:true})};
 const handleExam=(value:string)=>{const nextExam=normalizeExamCode(value);const nextSubject=resolvePreferredSubjectForExam(exams,nextExam,subject);setExam(nextExam);setSubject(nextSubject);persistStudySettings(updateSettings,{current_exam:nextExam,current_subject:nextSubject},"progress exam");replaceContext(nextExam,nextSubject,mentorMode)};
 const handleSubject=(value:string)=>{setSubject(value);persistStudySettings(updateSettings,{current_exam:exam,current_subject:value},"progress context");replaceContext(exam,value,mentorMode)};
 const handleMentor=(value:MentorMode)=>{setMentorMode(value);persistStudySettings(updateSettings,{mentor_mode:value,current_exam:exam,current_subject:subject},"progress mentor");replaceContext(exam,subject,value)};
 const available=subjects.filter(item=>item.available);const options=available.length?available:subjects;const examLabel=exams.find(item=>item.code===exam)?.label||exam.toUpperCase();const subjectLabel=subjects.find(item=>item.code===subject)?.label||subject.replace(/_/g," ");
 return <main className={styles.page}><PageHeader eyebrow={`${examLabel} · ${subjectLabel}`} title="Progress" description="Understand the next priority, then explore trends, revision, coaching evidence, and recent history." actions={<StudyContextControls exam={exam} subject={subject} mentorMode={mentorMode} exams={exams} subjects={options} onExamChange={handleExam} onSubjectChange={handleSubject} onMentorModeChange={handleMentor}/>}/><ProgressDashboard exam={exam} subject={subject} summary={summary} history={history} dailyPlan={plan} revisionDue={revision} coachSummary={coach} trends={trends} loading={loading} refreshing={refreshing} error={error} onRefresh={()=>void load(false)}/></main>
}
