import Head from "next/head"; import { useRouter } from "next/router"; import { useEffect,useRef,useState } from "react";
import { Button,LiveRegion,SelectField,StatusPanel } from "../components/ui"; import { LessonArticle } from "../components/tutor/LessonArticle"; import { TutorWorkspacePanels } from "../components/tutor/TutorWorkspacePanels"; import styles from "../components/tutor/TutorWorkspace.module.css";
import { DEFAULT_EXAM,DEFAULT_SUBJECT,askDoubt,createAudioRender,createVideoRender,downloadMediaRenderAsset,explainTopic,exportLesson,getMediaRenderJob,listMediaRenderJobs,type DoubtResponse,type ExamCode,type ExplainResponse,type LessonExportFormat,type LessonModeRequest,type MediaRenderJobResponse,type SubjectCode,type TeachingModeRequest } from "../lib/api";
import { useAuth } from "../lib/auth"; import { resolvePersistedExamContext,resolvePreferredSubjectForExam } from "../lib/exam-preferences"; import { isAdvancedLessonExport,isPremiumLessonMode,userHasFeature } from "../lib/premium"; import { persistStudySettings } from "../lib/settings-persistence"; import { LESSON_MODE_OPTIONS,TEACHING_MODE_OPTIONS } from "../lib/tutor-display"; import { useSubjects } from "../lib/useSubjects"; import { useTopics } from "../lib/useTopics";

const POLL_MS=2500;
function normalizeExam(value:string|null|undefined):ExamCode{return(value||DEFAULT_EXAM).trim().toLowerCase()}
function safeError(error:unknown,fallback:string){return error instanceof Error?error.message:fallback}
function triggerDownload(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url)}
function latest(jobs:MediaRenderJobResponse[],kind:"audio"|"scene"){const filtered=jobs.filter(job=>kind==="audio"?job.render_type==="audio":job.render_type!=="audio");return filtered.sort((a,b)=>Date.parse(b.updated_at||b.created_at||"")-Date.parse(a.updated_at||a.created_at||""))[0]||null}
function forLesson(job:MediaRenderJobResponse,lesson:ExplainResponse){return job.exam===lesson.exam&&job.subject===lesson.subject&&job.topic.trim().toLowerCase()===lesson.topic.trim().toLowerCase()&&(!job.lesson_mode||job.lesson_mode===lesson.lesson_mode)}

export default function TutorPage(){
 const router=useRouter();const{session,updateSettings}=useAuth();const[exam,setExam]=useState<ExamCode>(DEFAULT_EXAM);const{subjects,exams,defaultExam,defaultSubject,loading:subjectsLoading,error:subjectsError}=useSubjects(exam);const[subject,setSubject]=useState<SubjectCode>(DEFAULT_SUBJECT);const{topics,loading:topicsLoading,error:topicsError}=useTopics(subject,exam);const[topic,setTopic]=useState("");const[teachingMode,setTeachingMode]=useState<TeachingModeRequest>("auto");const[lessonMode,setLessonMode]=useState<LessonModeRequest>("auto");const[contextOpen,setContextOpen]=useState(false);
 const[lesson,setLesson]=useState<ExplainResponse|null>(null);const[lessonLoading,setLessonLoading]=useState(false);const[lessonError,setLessonError]=useState<string|null>(null);const[doubt,setDoubt]=useState<DoubtResponse|null>(null);const[doubtLoading,setDoubtLoading]=useState(false);const[doubtError,setDoubtError]=useState<string|null>(null);const[suggestedQuestion,setSuggestedQuestion]=useState("");const[suggestionToken,setSuggestionToken]=useState(0);
 const[exportLoading,setExportLoading]=useState<LessonExportFormat|null>(null);const[exportError,setExportError]=useState<string|null>(null);const[exportSuccess,setExportSuccess]=useState<string|null>(null);const[mediaLoading,setMediaLoading]=useState<"audio"|"scene"|null>(null);const[mediaDownloading,setMediaDownloading]=useState(false);const[mediaRefreshing,setMediaRefreshing]=useState(false);const[mediaError,setMediaError]=useState<string|null>(null);const[audioJob,setAudioJob]=useState<MediaRenderJobResponse|null>(null);const[sceneJob,setSceneJob]=useState<MediaRenderJobResponse|null>(null);
 const lessonRequest=useRef(0),doubtRequest=useRef(0),mediaRequest=useRef(0),exportRequest=useRef(0);const account=session?.user??null;const canPremiumModes=userHasFeature(account,"premium_lesson_modes");const canPremiumExports=userHasFeature(account,"lesson_exports");const mediaLocked=!canPremiumModes||!canPremiumExports||Boolean(lesson&&isPremiumLessonMode(lesson.lesson_mode)&&!canPremiumModes);

 useEffect(()=>{if(!router.isReady)return;const persisted=resolvePersistedExamContext(session?.settings,{defaultExam,defaultSubject});const qExam=typeof router.query.exam==="string"?normalizeExam(router.query.exam):persisted.exam;const qSubject=typeof router.query.subject==="string"?router.query.subject.trim():resolvePreferredSubjectForExam(exams,qExam,persisted.subject);setExam(qExam);setSubject(qSubject||DEFAULT_SUBJECT);if(typeof router.query.topic==="string")setTopic(router.query.topic.trim())},[router.isReady,router.query.exam,router.query.subject,router.query.topic,defaultExam,defaultSubject,exams,session?.settings]);
 useEffect(()=>{const available=subjects.filter(item=>item.available);if(!available.length)return;if(!available.some(item=>item.code===subject)){const next=defaultSubject||available[0].code;setSubject(next)}},[subjects,subject,defaultSubject]);
 useEffect(()=>{if(topics.length&&!topic)setTopic(topics[0])},[topics,topic]);
 useEffect(()=>()=>{lessonRequest.current++;doubtRequest.current++;mediaRequest.current++;exportRequest.current++},[]);
 useEffect(()=>{if(!lesson)return;const frame=window.requestAnimationFrame(()=>document.getElementById("lesson-title")?.focus());return()=>window.cancelAnimationFrame(frame)},[lesson]);
 useEffect(()=>{if(!lesson){setAudioJob(null);setSceneJob(null);return}const id=++mediaRequest.current;void listMediaRenderJobs({exam:lesson.exam,subject:lesson.subject,topic:lesson.topic,limit:24}).then(jobs=>{if(id!==mediaRequest.current)return;const scoped=jobs.filter(job=>forLesson(job,lesson));setAudioJob(latest(scoped,"audio"));setSceneJob(latest(scoped,"scene"))}).catch(()=>{if(id===mediaRequest.current){setAudioJob(null);setSceneJob(null)}})},[lesson]);
 useJobPoll(audioJob,setAudioJob,setMediaError);useJobPoll(sceneJob,setSceneJob,setMediaError);

 function syncRoute(nextExam:ExamCode,nextSubject:SubjectCode,nextTopic?:string){if(!router.isReady)return;void router.replace({pathname:router.pathname,query:{exam:nextExam,subject:nextSubject,...(nextTopic?{topic:nextTopic}:{})}},undefined,{shallow:true})}
 function changeExam(value:string){const next=normalizeExam(value),nextSubject=resolvePreferredSubjectForExam(exams,next,subject);setExam(next);setSubject(nextSubject);setTopic("");persistStudySettings(updateSettings,{current_exam:next,current_subject:nextSubject},"tutor exam");syncRoute(next,nextSubject)}
 function changeSubject(value:string){setSubject(value);setTopic("");persistStudySettings(updateSettings,{current_exam:exam,current_subject:value},"tutor context");syncRoute(exam,value)}
 function changeTopic(value:string){setTopic(value);syncRoute(exam,subject,value)}

 async function generate(){if(!topic||lessonLoading)return;if(LESSON_MODE_OPTIONS.find(o=>o.value===lessonMode)?.premium&&!canPremiumModes){setLessonError("This lesson mode is part of Premium. Payments are currently disabled; choose a standard lesson to continue.");return}const id=++lessonRequest.current;setLessonLoading(true);setLessonError(null);setDoubt(null);setDoubtError(null);setExportError(null);setExportSuccess(null);setMediaError(null);try{const response=await explainTopic(topic,subject,teachingMode,lessonMode,exam);if(id!==lessonRequest.current)return;setLesson(response);setTopic(response.topic);setContextOpen(false)}catch(error){if(id===lessonRequest.current)setLessonError(safeError(error,"The lesson could not be generated."))}finally{if(id===lessonRequest.current)setLessonLoading(false)}}
 async function ask(question:string){if(doubtLoading)return;const id=++doubtRequest.current;setDoubtLoading(true);setDoubtError(null);try{const grounding=lesson?[lesson.simple_explanation,lesson.key_points.join(" ")].join("\n"):null;const response=await askDoubt(lesson?.topic||topic,question,lesson?.subject||subject,grounding,lesson?.exam||exam);if(id===doubtRequest.current)setDoubt(response)}catch(error){if(id===doubtRequest.current)setDoubtError(safeError(error,"The tutor could not answer right now."))}finally{if(id===doubtRequest.current)setDoubtLoading(false)}}
 function suggest(question:string){setSuggestedQuestion(question);setSuggestionToken(v=>v+1)}
 async function downloadExport(format:LessonExportFormat){if(!lesson||exportLoading)return;if(isAdvancedLessonExport(format)&&!canPremiumExports){setExportError("This export is part of Premium. Payments are currently disabled; Markdown and plain text remain available.");return}const id=++exportRequest.current;setExportLoading(format);setExportError(null);setExportSuccess(null);try{const result=await exportLesson(lesson.topic,lesson.subject,lesson.teaching_mode,lesson.lesson_mode,lesson.exam,format);if(id!==exportRequest.current)return;triggerDownload(result.blob,result.filename);setExportSuccess(`${result.filename} is downloading.`)}catch(error){if(id===exportRequest.current)setExportError(safeError(error,"The lesson export could not be prepared."))}finally{if(id===exportRequest.current)setExportLoading(null)}}
 async function createMedia(kind:"audio"|"scene"){if(!lesson||mediaLoading||mediaLocked)return;const id=++mediaRequest.current;setMediaLoading(kind);setMediaError(null);try{const job=kind==="audio"?await createAudioRender(lesson.topic,lesson.subject,lesson.teaching_mode,lesson.lesson_mode,lesson.exam):await createVideoRender(lesson.topic,lesson.subject,lesson.teaching_mode,lesson.lesson_mode,lesson.exam,"narrated_video");if(id!==mediaRequest.current)return;if(kind==="audio")setAudioJob(job);else setSceneJob(job)}catch(error){if(id===mediaRequest.current)setMediaError(safeError(error,kind==="audio"?"Audio could not be queued.":"The scene package could not be queued."))}finally{if(id===mediaRequest.current)setMediaLoading(null)}}
 async function downloadMedia(job:MediaRenderJobResponse){if(!job.output.download_path||mediaDownloading)return;setMediaDownloading(true);setMediaError(null);try{const result=await downloadMediaRenderAsset(job.output.download_path);triggerDownload(result.blob,result.filename)}catch(error){setMediaError(safeError(error,"The artifact is unavailable. It may have expired or been removed."))}finally{setMediaDownloading(false)}}
 async function refreshMedia(){if(!lesson||mediaRefreshing)return;const id=++mediaRequest.current;setMediaRefreshing(true);setMediaError(null);try{const jobs=await listMediaRenderJobs({exam:lesson.exam,subject:lesson.subject,topic:lesson.topic,limit:24});if(id!==mediaRequest.current)return;const scoped=jobs.filter(job=>forLesson(job,lesson));setAudioJob(latest(scoped,"audio"));setSceneJob(latest(scoped,"scene"))}catch(error){if(id===mediaRequest.current)setMediaError(safeError(error,"Media status could not be refreshed."))}finally{if(id===mediaRequest.current)setMediaRefreshing(false)}}

 const subjectLabel=subjects.find(item=>item.code===subject)?.label||subject.split("_").join(" ");const examLabel=exams.find(item=>item.code===exam)?.label||exam.toUpperCase();const lessonSubjectLabel=lesson?(subjects.find(item=>item.code===lesson.subject)?.label||lesson.subject.split("_").join(" ")):subjectLabel;const lessonExamLabel=lesson?(exams.find(item=>item.code===lesson.exam)?.label||lesson.exam.toUpperCase()):examLabel;const selectedLessonOption=LESSON_MODE_OPTIONS.find(o=>o.value===lessonMode);
 const contextControls=<><div id="tutor-context-controls" className={styles.contextGrid}>
  <SelectField label="Exam" value={exam} onChange={e=>changeExam(e.target.value)} disabled={subjectsLoading}>{exams.map(item=><option key={item.code} value={item.code}>{item.label}</option>)}</SelectField>
  <SelectField label="Subject" value={subject} onChange={e=>changeSubject(e.target.value)} disabled={subjectsLoading}>{subjects.map(item=><option key={item.code} value={item.code} disabled={!item.available}>{item.label}{item.available?"":" (coming soon)"}</option>)}</SelectField>
  <SelectField label="Topic" value={topic} onChange={e=>changeTopic(e.target.value)} disabled={topicsLoading||!topics.length}>{topics.map(item=><option key={item} value={item}>{item}</option>)}</SelectField>
  <SelectField label="Teaching approach" value={teachingMode} onChange={e=>setTeachingMode(e.target.value as TeachingModeRequest)}>{TEACHING_MODE_OPTIONS.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</SelectField>
  <SelectField label="Lesson mode" value={lessonMode} onChange={e=>setLessonMode(e.target.value as LessonModeRequest)} helpText={selectedLessonOption?.description}>{LESSON_MODE_OPTIONS.map(item=><option key={item.value} value={item.value} disabled={Boolean(item.premium&&!canPremiumModes)}>{item.label}{item.premium?" · Premium":""}</option>)}</SelectField>
 </div><div className={styles.contextMeta}><span><strong>Chapter:</strong> {lesson?.chapter||"Resolved from the selected topic"}</span><span><strong>Language:</strong> English and Hindi text supported</span><span><strong>Context:</strong> {examLabel} · {subjectLabel}</span></div></>;
 const suggested=lesson?.clarification_prompts[0]||`What is the main exam trap in ${lesson?.topic||topic}?`;
 return <><Head><title>Tutor workspace | Adhyantra</title><meta name="description" content="Generate focused lessons, ask doubts, export notes, and prepare durable audio or scene packages."/></Head><main id="main-content" className={styles.page}>
  <header className={styles.intro}><div><div className={styles.eyebrow}>Study workspace · {examLabel} · {subjectLabel}</div><h1 className={styles.title}>Learn deeply. Act next.</h1><p className={styles.lede}>Build one focused lesson, read with clarity, and bring in assistance only when it helps.</p></div></header>
  {lesson?<details className={`${styles.context} ${styles.contextCompact}`} open={contextOpen} onToggle={event=>setContextOpen(event.currentTarget.open)}><summary className={styles.contextSummary}><span><span className={styles.summaryLabel}>Current lesson</span><strong>{lesson.topic}</strong><span className={styles.summaryMeta}>{lessonExamLabel} · {lessonSubjectLabel} · {TEACHING_MODE_OPTIONS.find(item=>item.value===lesson.teaching_mode)?.label||lesson.teaching_mode} · {LESSON_MODE_OPTIONS.find(item=>item.value===lesson.lesson_mode)?.label||lesson.lesson_mode}</span></span><span className={styles.editSetup}>Edit lesson setup</span></summary>{contextControls}</details>:<section className={styles.context} aria-labelledby="context-title"><div className={styles.setupIntro}><div><div className={styles.eyebrow}>Lesson setup</div><h2 id="context-title">Choose what to study</h2><p className={styles.hint}>Set the lesson context once. You can adjust it later without triggering a request.</p></div></div>{contextControls}<div className={styles.setupAction}><Button onClick={generate} loading={lessonLoading} disabled={!topic}>Generate lesson</Button><span>One request begins only when you choose Generate lesson.</span></div></section>}
  {subjectsError||topicsError?<StatusPanel tone="error" title="Study context unavailable" message={subjectsError||topicsError||"Try again."}/>:null}
  {lessonError?<div className={styles.lessonError}><StatusPanel tone="error" title="Lesson unavailable" message={lessonError} actions={<Button variant="secondary" onClick={generate}>Try again</Button>}/></div>:null}
  {lesson?<><section className={styles.lessonActions} aria-label="Lesson actions"><div><span className={styles.summaryLabel}>Ready to study</span><strong>{lesson.topic}</strong></div><div className={styles.actions}><Button onClick={()=>suggest(suggested)}>Ask a suggested doubt</Button><Button variant="secondary" onClick={generate} loading={lessonLoading}>Regenerate lesson</Button><Button variant="ghost" onClick={()=>window.print()}>Print lesson</Button></div></section><a className={styles.mobileAskLink} href="#tutor-tools">Jump to Ask, Export, and Media</a></>:null}
  <LiveRegion message={lessonLoading?"Generating the lesson.":lesson?"Lesson ready.":lessonError?"Lesson generation failed.":""}/>
  {lesson?<div className={styles.workspace}><div className={styles.main}><LessonArticle lesson={lesson} onAsk={suggest}/></div><aside id="tutor-tools" className={styles.rail} aria-label="Lesson tools"><TutorWorkspacePanels topic={lesson.topic} hasLesson doubtLoading={doubtLoading} doubtError={doubtError} doubt={doubt} suggestedQuestion={suggestedQuestion} suggestionToken={suggestionToken} suggestions={lesson.clarification_prompts} onAsk={ask} canExportPremium={canPremiumExports} exportLoading={exportLoading} exportError={exportError} exportSuccess={exportSuccess} onExport={downloadExport} mediaLocked={mediaLocked} mediaLoading={mediaLoading} mediaDownloading={mediaDownloading} mediaRefreshing={mediaRefreshing} mediaError={mediaError} audioJob={audioJob} sceneJob={sceneJob} onCreateMedia={createMedia} onDownload={downloadMedia} onRefresh={refreshMedia}/></aside></div>:<section className={styles.emptyWorkspace} aria-labelledby="empty-workspace-title"><div className={styles.emptyRule} aria-hidden="true"/><div><h2 id="empty-workspace-title">Your lesson will open here</h2><p>Choose a topic above, then generate a focused reading workspace with assistance and study utilities kept secondary.</p></div></section>}
 </main></>
}

function useJobPoll(job:MediaRenderJobResponse|null,setJob:(job:MediaRenderJobResponse)=>void,setError:(message:string|null)=>void){useEffect(()=>{if(!job||!(["queued","running"] as const).includes(job.lifecycle_state as "queued"|"running")||typeof window==="undefined")return;let cancelled=false;const timer=window.setTimeout(()=>{void getMediaRenderJob(job.id,job.render_type).then(next=>{if(!cancelled){setJob(next);setError(null)}}).catch(()=>{if(!cancelled)setError("Media status could not be refreshed. Try again in a moment.")})},POLL_MS);return()=>{cancelled=true;window.clearTimeout(timer)}},[job?.id,job?.lifecycle_state,job?.render_type,setJob,setError])}
